environment:

  matrix:
    - PYTHON: 'C:\Python37-x64'

install:
  - '%PYTHON%\python.exe -m pip install --upgrade pip'
  - '%PYTHON%\python.exe -m pip install poetry'
  - '%PYTHON%\Scripts\poetry.exe install --no-dev'

build: off

#test_script:
  #- 'ECHO 1'

after_test:
  - '%PYTHON%\Scripts\poetry.exe run pyinstaller --noconsole orts.py'
  - 'Xcopy /S /I /E data dist\orts\data'
  - 'Xcopy /S /I /E web dist\orts\web'

artifacts:
  - path: dist\orts
    name: orts-win64

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token:
    secure: OEoullMAEb45J6YSj44ciw06tsFn10stWFZ984EDtG6pzlUGI4vywC5iadJlG2av # encrypted
  draft: false
  prerelease: false
  force_update: true # in case travis released linux build first
  on:
    APPVEYOR_REPO_TAG: true # deploy on tag push only
