[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "orts"
version = "0.1.0"
description = "Simple HTML-based stream overlay"
authors = ["Nhan <nhan@nerdyweekly.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.20"
pycountry = "^18.5"
pefile = {version = "^2019.4", platform = "win32"}
pypiwin32 = {version = "^223.0", platform = "win32"}
pywin32-ctypes = {version = "^0.2.0", platform = "win32"}
pyinstaller = "^3.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.5"
ipdb = "^0.11.0"
python-language-server = "^0.26.1"
# jedi 0.17 breaks pyls so let's pin it to 0.16 until this gets merged:
# https://github.com/palantir/python-language-server/pull/781
jedi = "~0.16"
isort = "^4.3"
black = "^19.10b0"
